springfox:
 title: 'FINT Arbeidstaker Provider'
 version: '@version@'

spring:
 rabbitmq:
  host: squirrel.rmq.cloudamqp.com
  username: yqfycpqy
  password:
  virtual-host: yqfycpqy

  listener:
   retry:
    initial-interval: 3000
    max-attempts: 5
    max-interval: 10000
    multiplier: 1.5

logging.level.org.springframework.retry.support.RetryTemplate: DEBUG

fint.events.orgs: hfk.no, vaf.no, rogfk.no
