spring:
  application:
    name: fint-provider

fint:
  hazelcast:
    members: localhost
  provider:
    test-mode: false
    sse:
      heartbeat:
        enabled: true
      maxPoolSize: 10
      queueCapacity: 0
  audit:
    test-mode: true
  events:
    test-mode: true
    queue-endpoint-enabled: true
  springfox:
    swagger-https: false

server:
  port: 8081

logging:
  level:
    no.fint.provider.events.sse: DEBUG
