fint:
 hazelcast:
  members: localhost
 provider:
  test-mode: true
 audit:
  test-mode: true
 events:
  test-mode: true
  queue-endpoint-enabled: true

 springfox:
  swagger-https: false

server:
 port: 8081

logging:
 level:
  no.fint.provider.events.response: TRACE
  no.fint.provider.events.status: TRACE
