fint:
 provider:
  test-mode: true
 audit:
  test-mode: true
 events:
  test-mode: false

logging.level.com.spotify.docker.client.LoggingPullHandler: WARN

spring:
 rabbitmq:
  host: localhost
  username: guest
  password: guest
  virtual-host: /