spring:
  application:
    name: fint-provider

fint:
  hazelcast:
    members: localhost
  provider:
    assets:
      endpoint: https://admin.fintlabs.no/api/components/assets/administrasjon_personal
    sse:
      maxPoolSize: 10
      queueCapacity: 0
  audit:
    test-mode: true
  events:
    queue-endpoint-enabled: true
  springfox:
    swagger-https: false

server:
  port: 8081
