spring:
  application:
    name: fint-provider

fint:
  hazelcast:
    members: localhost
  provider:
    test-mode: true
    sse:
      maxPoolSize: 10
      queueCapacity: 0
  audit:
    test-mode: true
  springfox:
    swagger-https: false
