fint:
 provider:
  test-mode: true
 audit:
  test-mode: true
 rabbitmq:
  host: localhost
  port: 5672
  username: guest
  password: guest

logging.level.com.spotify.docker.client.LoggingPullHandler: WARN