version: "2"
services:

 rabbit:
  image: rabbitmq:3-management
  ports:
   - "15672:15672"
   - "5672:5672"

 fint-provider:
  image: "fint/provider"
  ports:
   - "8080:8080"
  links:
   - "elk"
   - "rabbit"
  logging:
    driver: "gelf"
    options:
     gelf-address: "udp://localhost:12201"
  environment:
   fint.rabbitmq.host: "rabbit"
   fint.rabbitmq.username: "guest"
   fint.rabbitmq.password: "guest"
   fint.provider.test-mode: "true"
   fint.audit.test-mode: "true"
   logging.level.root: INFO
   #logging.level.org.springframework.web: INFO