server:
 port: 8090

security:
 basic:
  enabled: false

fint:
 oauth:
  enabled: false
 events:
  queue-endpoint-enabled: true
  orgIds: mock.no

 relations:
  force-https: false
  default-base-url: http://localhost:8090